name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '5 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly


jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "Blog Posts Updated"
          committer_username:  "Blogs "
          readme_path: 'README.md, readme2.md'
          committer_email: "salman@scattr.io"
          user_agent: "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
          max_post_count: "5"
          feed_list: "https://blog.scattr.io/rss, https://codersalman.hashnode.dev/rss.xml"
